//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group6_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUs
    {
        public string companyAddress { get; set; }
        public string companyShippingPolicy { get; set; }
        public string companyReturnPolicy { get; set; }
        public string companyContactInfo { get; set; }
        public string companyBusinessDescription { get; set; }
        public int aboutUsID { get; set; }
    }
}
