//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group6_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails
    {
        public int emailNo { get; set; }
        public System.DateTime emailDate { get; set; }
        public string emailSubject { get; set; }
        public string emailBody { get; set; }
        public int customerID { get; set; }
        public int adminID { get; set; }
    
        public virtual Administrators Administrators { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
