//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group6_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDeliveries
    {
        public int stickerID { get; set; }
        public System.DateTime stickerDate { get; set; }
        public int customerID { get; set; }
        public int productID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
