//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group6_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswords
    {
        public int userID { get; set; }
        public string userAccountName { get; set; }
        public string userEncryptedPassword { get; set; }
        public int passwordExpiryTime { get; set; }
        public System.DateTime userAccountExpiryDate { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
